[package]
name = "ioxd_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
data_types = { path = "../data_types" }
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
router = { path = "../router" }
service_grpc_testing = { path = "../service_grpc_testing" }
time = { path = "../time" }
trace = { path = "../trace" }
trace_http = { path = "../trace_http" }


# Crates.io dependencies, in alphabetical order
async-trait = "0.1"

http = "0.2.0"
hyper = "0.14"
snafu = "0.7"

tonic = "0.6"
tonic-health = "0.6.0"
tonic-reflection = "0.3.0"
tokio = { version = "1.17", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.0" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
# Workspace dependencies, in alphabetical order
# Crates.io dependencies, in alphabetical order
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
regex = "1"
