[package]
name = "trace_exporters"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"
description = "Additional tracing exporters for IOx"

[dependencies]

async-trait = "0.1"
chrono = { version = "0.4" }
futures = "0.3"
observability_deps = { path = "../observability_deps" }
snafu = "0.6"
structopt = { version = "0.3.25" }
thrift = { version = "0.13.0" }
tokio = { version = "1.11", features = ["macros", "time", "sync", "rt"] }
trace = { path = "../trace" }

[dev-dependencies]
